### ISSUE TITLE
Set a rational ratio between initial frequency anf final frequency

### ISSUE THREAD

**Issue by kigafarz** [emgyrz/cubic_spline#1]
Would it be possible to have a rational sample frequency ratio between the finals points and the initials points? for example, now if I want a 3/2 ratio I have to set the variable "num_of_segments" at 2 to multiply the sample frequency by 3 and then only save one point every 2 points to get a 3/2 sample frequency ratio. It's work fine but points I don't need are calculated so it's is not very efficient in this use case.
The idea would be to only calculate the needed points in the case of a rational ratio.

**Comment by emgyrz** [comment]
Sorry, but it is hard for me to understand your case. It seems to be very special. Can you explain with code example? With what arguments you execute `Spline::xx` function, and what does your converter do, except it takes only every second point?
