### ISSUE TITLE
Tension per vertex

### ISSUE THREAD

**Issue by virtualritz** [emgyrz/cubic_spline#4]
Could support for specifying tension per vertex be added?
I'm using this crate to draw splines for some UI widget the user manipulates and I need to support a case where a single vertex is either smooth or hard (discontinuous).

**Comment by emgyrz** [comment]
Now I'm refactoring this repo. And after that or during, I will try to do what you ask. If everything goes well, I will add this option

**Comment by virtualritz** [comment]
Super nice, thank you!

**Comment by emgyrz** [comment]
@virtualritz now in version `0.9.8` this option has appeared.
